name: check migrations

on:
  push:
    branches:
      - main
      - maintenance
  pull_request:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process')
            //console.log(context)
            let firstCommit
            let lastCommit
            if (context.eventName === 'push') {
              console.log('-----')
              console.log(context.payload.commits[0])
              console.log('-----')
              console.log(context.payload.commits[context.payload.commits.length - 1])
              console.log('-----')
              console.log(context.payload.commits)
              console.log('-----')
              
              firstCommit=context.payload.commits[0][0].id
              lastCommit=context.payload.commits[0][context.payload.commits[0].length - 1].id
            } else if (context.eventName === 'pull_request') {
              firstCommit=context.payload.pull_request.base.sha
              lastCommit=context.payload.pull_request.head.sha
            } else {
              throw new Error('Unsupported event')
            }
            const rawFiles = execSync(`git diff --name-only --diff-filter=d "${firstCommit}~1" "${lastCommit}"`).toString()
            const files = rawFiles.split('\n').filter(Boolean)

            console.log(files)
